Controllers/Shared/GroupPriviligeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CFY_Exam.Models;
namespace CFY_Exam.Controllers.Shared
{
    public class GroupPriviligeController : Controller
    {

        private readonly CFYExamContext _context;

        public GroupPriviligeController(CFYExamContext context)
        {
            _context = context;
        }
        public IActionResult GroupPriviligeIndex()
        {
            using (var con = new CFYExamContext())
            {
                List<UserGroup> ug = _context.UserGroups.ToList() ;
              List<Privilege> priv = _context.Privileges.ToList();
                //ViewBag.UserGroups = ug;
                //ViewBag.Privileges = priv;
               //var rows = from myRow in con.UserGroups select myRow;
              //  var priv = from myRow1 in con.Privileges select myRow1;

               

                

            }
                return View();
        }
        [HttpPost]
        public void CreateGroupPrivilige(GroupPrivilige priv)
        {
            //Do something with formData
        }
    }
}

Controllers/Shared/PriviligeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Globalization;
using CFY_Exam.Models;
using Microsoft.AspNetCore.Mvc;


namespace CFY_Exam.Controllers.Shared
{
    public class PriviligeController : Controller
    {
        public IActionResult PriviligeIndex()
        {
            return View();
        }

        [HttpPost]
        public void CreatePrivilige(Privilege priv)
        {
            using (var con = new CFYExamContext())
            {
                string privcode = priv.PriviligeCode;
                string privname = priv.PriviligeName;
                int privtype = priv.PriviligeType;
                DateTime currenttime = DateTime.Now;
                var privt = new Privilege();
                privt.PriviligeCode = privcode;
                privt.PriviligeName = privname;
                privt.PriviligeType = privtype;
                privt.Status = priv.Status;
                privt.FirstUserName = "first username";
                privt.FirstTimeStamp = currenttime;

                con.Privileges.Add(privt);
                con.SaveChanges();
            }
            //Console.WriteLine("code : " + privcode + "groupname : " + privname + "priv type : " + privtype + "status : " + status);

        }

        public IActionResult CreatePrivilgewithGroup()
        {
            return View();
        }

        public IActionResult CreateUpdatePrivilgewithGroup()
        {
            return View();
        }
    }
}

Controllers/Shared/UserGroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CFY_Exam.Models;

namespace CFY_Exam.Controllers.Shared
{
    public class UserGroupController : Controller
    {
        public IActionResult GroupIndex()
        {
            return View();
        }

        [HttpPost]
        public void CreateUserGroup(UserGroup gr)
        {
           

            using (var con = new CFYExamContext())
            {
                string code = gr.UserGroupCode;
                string groupname = gr.GroupName;
              
                
                DateTime currenttime = DateTime.Now;
                var ug = new UserGroup();
                ug.UserGroupCode = code;
                ug.GroupName = groupname;
                ug.Status = gr.Status;
                ug.FirstTimeStamp = currenttime;
                ug.FirstUserName = "First User Name";

                con.UserGroups.Add(ug);
                con.SaveChanges();
            }
                //Console.WriteLine("code : " + code + "groupname : " + groupname + "status : " + grstatus);

        }

        public IActionResult CreateUserwithGroup()
        {
            return View();
        }

        public IActionResult CreateUpdatewithGroup()
        {
            return View();
        }

      
    }
}

Views/Shared/GroupIndex.cshtml
@using CFY_Exam;
@model CFY_Exam.Models.UserGroup;

@{
    ViewData["Title"] = "GroupIndex";
}

<h1>GroupIndex</h1>

<!DOCTYPE html>
<html lang="en">
<head>
   
    <!--===============================================================================================-->
</head>
<body>
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">

                <h2>Create User Groups</h2>
                <div style="border:solid">
                    @using (Html.BeginForm("CreateUserGroup", "UserGroup", FormMethod.Post))
                    {
                        <b>Enter Group Code </b>@Html.TextBoxFor(m => m.UserGroupCode) <br />
                        <b>Enter Group Name </b>@Html.TextBoxFor(m => m.GroupName) <br />
                        <b>Select Status of the Group </b> @Html.DropDownListFor(m => m.Status, new List<SelectListItem> { new SelectListItem { Text = "Active", Value = "1", Selected = true }, new SelectListItem { Text = "Inactive", Value = "2" } }, "Select Group Status") <br />
                        <input type="submit" value="Create User Group" />
                    }
                </div>
                <h2>Update User Groups</h2>
                <div style="border:solid">
                    @using (Html.BeginForm("CreateUserGroup", "UserGroup", FormMethod.Post))
                    {
                        <b>Enter Group Code </b>@Html.TextBoxFor(m => m.UserGroupCode) <br />
                        <b>Enter Group Name </b>@Html.TextBoxFor(m => m.GroupName) <br />
                        <b>Select Status of the Group </b> @Html.DropDownListFor(m => m.Status, new List<SelectListItem> { new SelectListItem { Text = "Active", Value = "1", Selected = true }, new SelectListItem { Text = "Inactive", Value = "2" } }, "Select Group Status") <br />
                        <input type="submit" value="Create User Group" />
                    }
                </div>





                    <!--===============================================================================================-->
                    <script src="~/lib/Login1/vendor/jquery/jquery-3.2.1.min.js"></script>
                    <!--===============================================================================================-->
                    <script src="~/lib/Login1/vendor/animsition/js/animsition.min.js"></script>
                    <!--===============================================================================================-->
                    <script src="~/lib/Login1/vendor/bootstrap/js/popper.js"></script>
                    <script src="~/lib/Login1/vendor/bootstrap/js/bootstrap.min.js"></script>
                    <!--===============================================================================================-->
                    <script src="~/lib/Login1/vendor/select2/select2.min.js"></script>
                    <!--===============================================================================================-->
                    <script src="~/lib/Login1/vendor/daterangepicker/moment.min.js"></script>
                    <script src="~/lib/Login1/vendor/daterangepicker/daterangepicker.js"></script>
                    <!--===============================================================================================-->
                    <script src="~/lib/Login1/vendor/countdowntime/countdowntime.js"></script>
                    <!--===============================================================================================-->
                    <script src="~/lib/Login1/js/main.js"></script>
                </div>
            </div>
    </div>
</body>
</html>

Views/Shared/GroupPriviligeIndex.cshtml
@using CFY_Exam;
@model CFY_Exam.Models.GroupPrivilige;
@{
    ViewData["Title"] = "GroupPriviligeIndex";
}

<h1>GroupPriviligeIndex</h1>
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login - CFY Exam</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="~/lib/Login1/images/icons/favicon.ico" />
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/lib/Login1/vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/lib/Login1/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/lib/Login1/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/lib/Login1/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/lib/Login1/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/lib/Login1/vendor/animsition/css/animsition.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/lib/Login1/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/lib/Login1/vendor/daterangepicker/daterangepicker.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/lib/Login1/css/util.css">
    <link rel="stylesheet" type="text/css" href="~/lib/Login1/css/main.css">
    <!--===============================================================================================-->
</head>
<body>
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">
                <h2>Relate Groups with Priviliges</h2>
                <div style="border:solid">
                    <!-- @using (Html.BeginForm("CreateGroupPrivilige", "GroupPrivilige", FormMethod.Post))
        {
            <b>Select User Group</b>
            <table>


                <tr>
                 <td>@Html.CheckBox("This is the text", true)</td>
                </tr>


                <b>Select Priviliges</b>

                foreach (var h in ViewBag.Priviliges)
                {

                <tr>
                    <td>@Html.CheckBox("This is the text in privilige", false)</td>
                </tr>
                }
            </table>
        }


        } -->
    </div>  
                    <input type="checkbox" id="vehicle1" name="vehicle1" value="Bike">
                    <label for="vehicle1"> I have a bike</label><br>
                    <input type="checkbox" id="vehicle2" name="vehicle2" value="Car">
                    <label for="vehicle2"> I have a car</label><br>
                    <input type="checkbox" id="vehicle3" name="vehicle3" value="Boat">
                    <label for="vehicle3"> I have a boat</label><br>

                    <!--===============================================================================================-->
                    <script src="~/lib/Login1/vendor/jquery/jquery-3.2.1.min.js"></script>
                    <!--===============================================================================================-->
                    <script src="~/lib/Login1/vendor/animsition/js/animsition.min.js"></script>
                    <!--===============================================================================================-->
                    <script src="~/lib/Login1/vendor/bootstrap/js/popper.js"></script>
                    <script src="~/lib/Login1/vendor/bootstrap/js/bootstrap.min.js"></script>
                    <!--===============================================================================================-->
                    <script src="~/lib/Login1/vendor/select2/select2.min.js"></script>
                    <!--===============================================================================================-->
                    <script src="~/lib/Login1/vendor/daterangepicker/moment.min.js"></script>
                    <script src="~/lib/Login1/vendor/daterangepicker/daterangepicker.js"></script>
                    <!--===============================================================================================-->
                    <script src="~/lib/Login1/vendor/countdowntime/countdowntime.js"></script>
                    <!--===============================================================================================-->
                    <script src="~/lib/Login1/js/main.js"></script>
                </div>
        </div>
    </div>
</body>
</html>

Views/Shared/PriviligeIndex.cshtml
@using CFY_Exam;
@model CFY_Exam.Models.Privilege;
@{
    ViewData["Title"] = "PriviligeIndex";
}

<h1>PriviligeIndex</h1>
<!DOCTYPE html>
<html lang="en">
<head>
   
    <!--===============================================================================================-->
</head>
<body>
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100 p-l-85 p-r-85 p-t-55 p-b-55">
                <h2>Create Priviliges</h2>
                <div style="border:solid">
                    @using (Html.BeginForm("CreatePrivilige", "Privilige", FormMethod.Post))
                    {
                        <b>Enter Privilige Code </b>@Html.TextBoxFor(m => m.PriviligeCode) <br />
                        <b>Enter Privilige Name </b>@Html.TextBoxFor(m => m.PriviligeName) <br />
                        <b>Enter Privilige Type </b>@Html.TextBoxFor(m => m.PriviligeType) <br />
                        <b>Select Status of the Privilige </b>@Html.DropDownListFor(m =>m.Status, new List<SelectListItem> { new SelectListItem { Text = "Active", Value = "1", Selected = true }, new SelectListItem { Text = "Inactive", Value = "2" } }, "Select Privilige Status") <br />
                        <input type="submit" value="Create Privilige" />
                    }
                </div>

                <!--===============================================================================================-->
                <script src="~/lib/Login1/vendor/jquery/jquery-3.2.1.min.js"></script>
                <!--===============================================================================================-->
                <script src="~/lib/Login1/vendor/animsition/js/animsition.min.js"></script>
                <!--===============================================================================================-->
                <script src="~/lib/Login1/vendor/bootstrap/js/popper.js"></script>
                <script src="~/lib/Login1/vendor/bootstrap/js/bootstrap.min.js"></script>
                <!--===============================================================================================-->
                <script src="~/lib/Login1/vendor/select2/select2.min.js"></script>
                <!--===============================================================================================-->
                <script src="~/lib/Login1/vendor/daterangepicker/moment.min.js"></script>
                <script src="~/lib/Login1/vendor/daterangepicker/daterangepicker.js"></script>
                <!--===============================================================================================-->
                <script src="~/lib/Login1/vendor/countdowntime/countdowntime.js"></script>
                <!--===============================================================================================-->
                <script src="~/lib/Login1/js/main.js"></script>
            </div>
        </div>
    </div>
</body>
</html>

Views/Shared/_Layout_1.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CFY_Exam</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CFY_Exam</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CFY_Exam - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>